FROM isaac_ros_dev-aarch64

RUN mkdir /opt/unitree && cd /opt/unitree && \
    git clone https://github.com/unitreerobotics/unitree_ros2 && \
    cd unitree_ros2/cyclonedds_ws/src && \
    git clone https://github.com/ros2/rmw_cyclonedds -b humble && \
    git clone https://github.com/eclipse-cyclonedds/cyclonedds -b releases/0.10.x && \
    git clone https://github.com/ros2/rosidl_dds -b humble && \
    cd .. && . /opt/ros/$ROS_DISTRO/setup.sh && \
    colcon build --packages-select cyclonedds rosidl_generator_dds_idl && \
    . install/setup.sh && colcon build


RUN mkdir -p /opt/isaac_ros/src

WORKDIR /opt/isaac_ros/src

RUN cd /opt/isaac_ros/src && \
    git clone https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common.git -b release-2.1 && \
    git clone https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_nitros.git -b release-2.1
RUN cd /opt/isaac_ros/src && \
    git clone https://github.com/osrf/negotiated && \
    git clone https://github.com/samcts-auki/isaac_ros_visual_slam -b g1-isaac-vslam && \
    cd .. && . /opt/ros/$ROS_DISTRO/setup.sh && \
    colcon build
